  	
</div>
</div><!--- rightSideContent --->

</div><!---  main  ---->

<div style="float:left; width: 100%; border-top:2px solid #ddd; padding:10px 0px;">
<p style="padding: 0px 20px 0px 20px;"><a href="https://idsproject.org/index.aspx"><img alt="IDS Project" src="includes/IDSProject-small-logo.png" style="vertical-align:middle;"></a>&nbsp; <a href="https://www.geneseo.edu/library">Milne Library</a> is the home of the award winning <a href="https://idsproject.org/index.aspx">IDS Project</a>, a collaboration of over 100 libraries supporting and enhancing resource sharing.</p>
<p style="padding: 0px 20px 0px 20px;">IDS is powered by <a href="http://www.atlas-sys.com/illiad/" target="_blank">ILLiad</a>.</p>
</div> 


  </body>
</html>