<!DOCTYPE html>
<html lang="en">
<!-- This file contains styles, scripts and other information that goes in the 
head of each document that takes Milne Library styles and javascripts, Geneseo styles and icons, GIST4Web styles -->
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7, IE=EmulateIE9, IE=EDGE" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="default" />
<link rel="apple-touch-icon" href="iphone-icon.png" />
      <meta charset="utf-8" />
{ <link rel="shortcut icon" href="https://www.geneseo.edu/sites/all/themes/geneseo_library/favicon.ico" type="image/x-icon" /> }


  <!--INTRANET LIB CUSTOM STYLES & JQUERY LIBRARIES -->
  <!-- put the path to your GIST4Web.css styleshett here -->
{ <link rel="stylesheet" type="text/css" href="https://illiad.geneseo.edu/styles/GIST4Web.css" media="all"> }
   <!--END INTRANET LIB CUSTOM STYLES & JQUERY LIBRARIES -->
	


<body>
    

<div><!---  main  --->

{ UNCOMMENT areas BELOW and replace with your own logo and breadcrumb trail as needed --> }

{ <div style="height: 20px;width: 100%; margin: 0px ! important;background-color: #345290;"></div> }

<div style="margin:0px 20px 20px 20px;">
<div style="width: 100%;">   
        
{ <div style="float:left; margin-top:-20px;">
<a href="https://www.geneseo.edu/library"><img alt="Milne Library SUNY Geneseo" title="Milne Library SUNY Geneseo" src="https://eres.geneseo.edu/milne-logo/milne-library-logo.png" style="width:85%;" /></a> 
</div>    	
</div> }
		
<div class="breadcrumb" style="margin-top:20px;">
{ <div>
<a href="https://www.geneseo.edu/">SUNY Geneseo</a>
&raquo; <a href="https://www.geneseo.edu/library">Milne Library</a>
&raquo; <a href="https://illiad.geneseo.edu" style="color:#b85533 !important;">Information Delivery Services</a>
</div> }
</div>
<div id="rightSideContent" >
<!--- BODY CONTENT RIGHT SIDE  BEGINS --->